window: 12
horizon: 12
batch_size: 64
l2_reg: 0.0001
use_lr_schedule: True
lr: 0.001
epochs: 150

hidden_size: 32
ff_size: 256
n_layers: 4
dropout: 0.1
temporal_kernel_size: 2
spatial_kernel_size: 2
dilation: 2
norm: batch