window: 12
horizon: 12
batch_size: 64
l2_reg: 0.0001
use_lr_schedule: True
lr: 0.001
epochs: 100

hidden_size: 32
ff_size: 64
kernel_size: 2
n_convs_layer: 2
n_layers: 4
dropout: 0.1
resnet: true
norm: batch
dilation: 2